<a href="https://colab.research.google.com/github/Gabriel1000000/IA_aps-anlise-de-dados-/blob/main/IA_aps(anlise_de_dados).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Biblioteca de analise de dados
import pandas as pd

# Bibliotecas de Aprendizado de MÃ¡quina
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00519/heart_failure_clinical_records_dataset.csv'
dados = pd.read_csv(url, header=None)
dados=dados.drop(0)
coluna_nome = ['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction', 'high_blood_pressure', 'platelets', 'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time', 'DEATH_EVENT']
dados.columns = coluna_nome
dados

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
1,75,0,582,0,20,1,265000,1.9,130,1,0,4,1
2,55,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
3,65,0,146,0,20,0,162000,1.3,129,1,1,7,1
4,50,1,111,0,20,0,210000,1.9,137,1,0,7,1
5,65,1,160,1,20,0,327000,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,62,0,61,1,38,1,155000,1.1,143,1,1,270,0
296,55,0,1820,0,38,0,270000,1.2,139,0,0,271,0
297,45,0,2060,1,60,0,742000,0.8,138,0,0,278,0
298,45,0,2413,0,38,0,140000,1.4,140,1,1,280,0
299,50,0,196,0,45,0,395000,1.6,136,1,1,285,0

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 1 to 299
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    object
 1   anaemia                   299 non-null    object
 2   creatinine_phosphokinase  299 non-null    object
 3   diabetes                  299 non-null    object
 4   ejection_fraction         299 non-null    object
 5   high_blood_pressure       299 non-null    object
 6   platelets                 299 non-null    object
 7   serum_creatinine          299 non-null    object
 8   serum_sodium              299 non-null    object
 9   sex                       299 non-null    object
 10  smoking                   299 non-null    object
 11  time                      299 non-null    object
 12  DEATH_EVENT               299 non-null    object
dtypes: object(13)
memory usage: 30.5+ KB

In [ ]:
dados.head(10)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
1,75,0,582,0,20,1,265000,1.9,130,1,0,4,1
2,55,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
3,65,0,146,0,20,0,162000,1.3,129,1,1,7,1
4,50,1,111,0,20,0,210000,1.9,137,1,0,7,1
5,65,1,160,1,20,0,327000,2.7,116,0,0,8,1
6,90,1,47,0,40,1,204000,2.1,132,1,1,8,1
7,75,1,246,0,15,0,127000,1.2,137,1,0,10,1
8,60,1,315,1,60,0,454000,1.1,131,1,1,10,1
9,65,0,157,0,65,0,263358.03,1.5,138,0,0,10,1

In [ ]:
dados.tail(10)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
290,90,1,337,0,38,0,390000,0.9,144,0,0,256,0
291,45,0,615,1,55,0,222000,0.8,141,0,0,257,0
292,60,0,320,0,35,0,133000,1.4,139,1,0,258,0
293,52,0,190,1,38,0,382000,1,140,1,1,258,0
294,63,1,103,1,35,0,179000,0.9,136,1,1,270,0
295,62,0,61,1,38,1,155000,1.1,143,1,1,270,0
296,55,0,1820,0,38,0,270000,1.2,139,0,0,271,0
297,45,0,2060,1,60,0,742000,0.8,138,0,0,278,0
298,45,0,2413,0,38,0,140000,1.4,140,1,1,280,0
299,50,0,196,0,45,0,395000,1.6,136,1,1,285,0

In [ ]:
contagem = dados['age'].value_counts()
contagem

60        33
50        27
65        26
70        25
45        19
55        17
75        11
53        10
58        10
63         8
80         7
72         7
40         7
42         7
85         6
68         5
52         5
62         5
51         4
59         4
61         4
73         4
49         4
69         3
46         3
64         3
82         3
90         3
78         2
60.667     2
54         2
77         2
57         2
66         2
44         2
67         2
95         2
48         2
43         1
86         1
81         1
79         1
41         1
94         1
87         1
47         1
56         1
Name: age, dtype: int64

In [ ]:
y = dados['age']
x = dados.iloc[:,1:]
x.head()

,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
1,0,582,0,20,1,265000,1.9,130,1,0,4,1
2,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
3,0,146,0,20,0,162000,1.3,129,1,1,7,1
4,1,111,0,20,0,210000,1.9,137,1,0,7,1
5,1,160,1,20,0,327000,2.7,116,0,0,8,1